services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: btb_timescaledb
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  neo4j:
    image: neo4j:latest
    container_name: btb_neo4j
    env_file: .env
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7474/browser"]
      interval: 10s
      timeout: 5s
      retries: 5

  fuseki:
    image: apache/jena-fuseki:latest
    container_name: btb_fuseki
    env_file: .env
    ports:
      - "3030:3030"
    environment:
      ADMIN_PASSWORD: ${FUSEKI_ADMIN_PASSWORD}
    volumes:
      - fuseki_data:/fuseki
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3030"]
      interval: 10s
      timeout: 5s
      retries: 5

  memgraph:
    image: memgraph/memgraph:latest
    container_name: btb_memgraph
    ports:
      - "7688:7687"
    volumes:
      - memgraph_data:/var/lib/memgraph
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/7687'" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  timescaledb_data:
  neo4j_data:
  neo4j_logs:
  fuseki_data:
  memgraph_data:
